[General]
app=oskar_sim_interferometer
version=2.12.2

[sky]
fileset

[observation]
freqset
num_channels=1
frequency_inc_hz=1.4E+5
phase_centre_ra_deg=0.0
phase_centre_dec_deg=-27.0
num_time_steps=24
length=4:00:00.00
# Central time is 05:30:00.00 UTC
start_time_utc=2025-03-03 03:30:00.00

[telescope]
input_directory=SKA-Low_AAstar_original_rigid-rotation.tm
aperture_array/element_pattern/enable_numerical=false
aperture_array/array_pattern/element/x_gain=1.0
aperture_array/array_pattern/element/y_gain=1.0
aperture_array/array_pattern/element/x_gain_error_time=0.0015057
aperture_array/array_pattern/element/y_gain_error_time=0.0015057
aperture_array/array_pattern/element/x_phase_error_fixed_deg=0.0
aperture_array/array_pattern/element/y_phase_error_fixed_deg=0.0
aperture_array/array_pattern/element/x_phase_error_time_deg=0.0015057
aperture_array/array_pattern/element/y_phase_error_time_deg=0.0015057

[interferometer]
channel_bandwidth_hz=1.4E+5
time_average_sec=10.0
oskar_vis_filename=output/vis
ms_filename=output/sim.ms
